name: tracker
description: "A premium expense tracker app with data persistence and beautiful charts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
